#pragma once

#ifndef CPPREFLECT17_STRINGIFY
    #define CPPREFLECT17_STRINGIFY( a ) #a 
#endif

#ifndef CPPREFLECT17_EVAL
    #define CPPREFLECT17_EVAL0(...) __VA_ARGS__
    #define CPPREFLECT17_EVAL1(...) CPPREFLECT17_EVAL0(CPPREFLECT17_EVAL0(CPPREFLECT17_EVAL0(__VA_ARGS__)))
    #define CPPREFLECT17_EVAL2(...) CPPREFLECT17_EVAL1(CPPREFLECT17_EVAL1(CPPREFLECT17_EVAL1(__VA_ARGS__)))
    #define CPPREFLECT17_EVAL3(...) CPPREFLECT17_EVAL2(CPPREFLECT17_EVAL2(CPPREFLECT17_EVAL2(__VA_ARGS__)))
    #define CPPREFLECT17_EVAL4(...) CPPREFLECT17_EVAL3(CPPREFLECT17_EVAL3(CPPREFLECT17_EVAL3(__VA_ARGS__)))
    #define CPPREFLECT17_EVAL(...) CPPREFLECT17_EVAL4(CPPREFLECT17_EVAL4(CPPREFLECT17_EVAL4(__VA_ARGS__)))
#endif

#ifndef CPPREFLECT17_MAP
    #define CPPREFLECT17_END(...)
    #define CPPREFLECT17_OUT

    #define CPPREFLECT17_EMPTY() 
    #define CPPREFLECT17_DEFER(id) id CPPREFLECT17_EMPTY()

    #define CPPREFLECT17_MAP_END2() 0, CPPREFLECT17_END
    #define CPPREFLECT17_MAP_END1(...) CPPREFLECT17_MAP_END2
    #define CPPREFLECT17_MAP_END(...) CPPREFLECT17_MAP_END1
    #define CPPREFLECT17_MAP_NEXT0(test, next, ...) next CPPREFLECT17_OUT
    #define CPPREFLECT17_MAP_NEXT1(test, next) CPPREFLECT17_DEFER ( CPPREFLECT17_MAP_NEXT0 ) ( test, next, 0)
    #define CPPREFLECT17_MAP_NEXT(test, next)  CPPREFLECT17_MAP_NEXT1(CPPREFLECT17_MAP_END test, next)
    #define CPPREFLECT17_MAP0(f, x, peek, ...) f(x) CPPREFLECT17_DEFER ( CPPREFLECT17_MAP_NEXT(peek, CPPREFLECT17_MAP1) ) ( f, peek, __VA_ARGS__ ) 
    #define CPPREFLECT17_MAP1(f, x, peek, ...) f(x) CPPREFLECT17_DEFER ( CPPREFLECT17_MAP_NEXT(peek, CPPREFLECT17_MAP0) ) ( f, peek, __VA_ARGS__ )

    /**  `Map` like For-Each on a Variadic macro
     * @todo DOC: This was inspired by some stackoverflow somewhere!
     * @code 
     * CPPREFLECT17_MAP( ForEachMacro, __VA_ARGS__ ) };
     * @endcode 
    */
    #define CPPREFLECT17_MAP(f, ...) CPPREFLECT17_EVAL(CPPREFLECT17_MAP1(f, __VA_ARGS__, ()()(), ()()(), ()()(), 0))
#endif